name: LOSAS
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: jadedResearcher <gtg287y@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  source_map_stack_trace: any

dev_dependencies:
  TextEngine:
    git:
      url: git://github.com/FarragoFiction/TextEngine.git
      ref: Dart-2.2.0
  DollLibCorrect:
    git:
      url: git://github.com/FarragoFiction/DollLibCorrect.git
      ref: Dart-2.2.0
  recase: ^2.0.1
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
